Fix supress_redcapr_messages Bug
CHOP-CGTInformatics/REDCapTidieR pull request #115
Opened 2022-12-15 17:32 UTC by rsh52

# Description
This PR provides a quick solution to `suppress_redcapr_messages`, which currently does not get fed to any REDCapR API calls since we set `verbose = FALSE` for everything. 

A funny side effect of the way we named this argument is that REDCapR `verbose` and REDCapTidieR `suppress` mean the opposite things, so it isn't a 1:1 slot in. Instead all API calls now have `verbose = if(suppress_redcapr_messages){FALSE}else{TRUE}` to switch the logic and line up with how our argument reads. 

> I.e., if we **do** want messages suppressed, then we **don't** want REDCapR to be verbose and vice-versa.

I have not written a test for this, I'm not sure for something this small we need one, but am open to writing one up if desired. Also left a note about the bullet "New/revised functions don't repeat code" in the checklist.

# Proposed Changes 
List changes below in bullet format:

- Update all REDCapR API function calls from `verbose = FALSE` to `verbose = if(suppress_redcapr_messages){FALSE}else{TRUE}`
- Add `suppress_redcapr_messages` as a parameter for applicable functions where it wasn't one before

### Issue Addressed
**Closes #104**

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [NA] New/revised functions have associated tests
- [NA] New/revised functions that update downstream outputs have associated static testing files (`.RDS`) updated under `inst/testdata/create_test_data.R`
- [NA] New tests that make API calls use `httptest::with_mock_api` and any new mocks were added to `tests/testthat/fixtures/create_httptest_mocks.R`
- [NA] New/revised functions use appropriate naming conventions
- [ ] New/revised functions don't repeat code
   - Technically repeats conditional switching logic at all API calls
- [x] Code changes are less than **250** lines total
- [x] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] The appropriate reviewer is assigned to the PR
- [x] The appropriate developers are assigned to the PR

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [ ] I checked that new files follow naming conventions and are in the right place
- [ ] I checked that documentation is complete, clear, and without typos
- [ ] I added/edited comments to explain "why" not "how"
- [ ] I checked that all new variable and function names follow naming conventions
- [ ] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [ ] I checked that new tests address important edge cases

2022-12-15 18:32 UTC, ezraporter requested changes
Can we change all the:
```r
    verbose = if (suppress_redcapr_messages) {
      FALSE
    } else {
      TRUE
    }
```

to:
```r
verbose = !suppress_redcapr_messages
```

One #114 is merged we'll have arg checking to make sure `suppress_redcapr_messages` is atomic logical anyways

2022-12-15 18:32 UTC, ezraporter commented on R/read_redcap.R
> +    }
```suggestion
    verbose = !suppress_redcapr_messages
```

2022-12-15 19:14 UTC, rsh52 commented on R/read_redcap.R
> +    }
Much better, changing now

2022-12-15 19:38 UTC, ezraporter approved these changes

2022-12-16 04:13 UTC, skadauke approved these changes
LGTM!

2022-12-16 12:24 UTC, merged